import {
  Stethoscope,
  Heart,
  Hospital,
  Pill,
  Activity,
  Shield,
  Users,
  Calendar,
  FileText,
  Bell,
  Settings,
  Home,
  MessageSquare,
  MapPin,
  Thermometer,
  Brain,
  Syringe,
  Ambulance,
  type LucideProps,
} from "lucide-react";

export const HealthcareIcons = {
  Stethoscope: (props: LucideProps) => <Stethoscope {...props} />,
  Heart: (props: LucideProps) => <Heart {...props} />,
  Hospital: (props: LucideProps) => <Hospital {...props} />,
  Pill: (props: LucideProps) => <Pill {...props} />,
  Activity: (props: LucideProps) => <Activity {...props} />,
  Shield: (props: LucideProps) => <Shield {...props} />,
  Users: (props: LucideProps) => <Users {...props} />,
  Calendar: (props: LucideProps) => <Calendar {...props} />,
  FileText: (props: LucideProps) => <FileText {...props} />,
  Bell: (props: LucideProps) => <Bell {...props} />,
  Settings: (props: LucideProps) => <Settings {...props} />,
  Home: (props: LucideProps) => <Home {...props} />,
  MessageSquare: (props: LucideProps) => <MessageSquare {...props} />,
  MapPin: (props: LucideProps) => <MapPin {...props} />,
  Thermometer: (props: LucideProps) => <Thermometer {...props} />,
  Brain: (props: LucideProps) => <Brain {...props} />,
  Syringe: (props: LucideProps) => <Syringe {...props} />,
  Ambulance: (props: LucideProps) => <Ambulance {...props} />,
};

export {
  Stethoscope,
  Heart,
  Hospital,
  Pill,
  Activity,
  Shield,
  Users,
  Calendar,
  FileText,
  Bell,
  Settings,
  Home,
  MessageSquare,
  MapPin,
  Thermometer,
  Brain,
  Syringe,
  Ambulance,
};
  
